### PR TITLE
handle off season

### LINKED ISSUE #19: Doesn't work in the MLB off-season
Either load fake schedule data and current standing, or just exit when the MLB season is over.

### PR DESCRIPTION
**Pull request by rhagarty**
Keeps archived data for use during off season.
This data will be used if `exports.offSeason = true;` is set in config.js

Closes #19

### CODE REVIEW

File: run.js [hunk 1]
```diff
@@ -123,6 +138,15 @@ function getMlbTeams() {
     REQUEST(options)
       .then(function (response) {
         mlbTeams = JSON.parse(response);
+
+        if (saveData) {
```
Comment (stevemar) [inline run.js]: where's `saveData` getting modified? i only see it being set on L27.

Comment (rhagarty) [reply run.js]: Yeah, it's kinda a one shot deal to write out the current data to files. I didn't want to delete in case I needed to do it again. I will document it better.

Comment (rhagarty) [reply run.js]: Actually, I think it best to delete this and put it into a separate script that can be run outside of the main code. So hold off on any more reviews.

**Comment by rhagarty** [comment]
Now the  save data function is moved into a separate script in the lib directory.

**Review by stevemar — APPROVED** [review]
much cleaner separation!
